import abc
import mtgcompiler.AST.core as core
from enum import Enum

class MgAbstractType(core.MgNode):
        """MgAbstractType is an uninstantiable parent class for types, subtypes, and supertypes. 
        It provides the functionalities common to all (sub|super)*type objects."""
        
        def setValue(self, value):
                """Setter method for the value attribute. This is the value held by the type object. 
                It can either be a pre-defined Enum type, or a string in the case of a custom (sub|super)*type."""
                self._value=value
        
        def getValue(self):
                """Access method for the value attribute. This is the value held by the type object. 
                It can either be a pre-defined Enum type, or a string in the case of a custom (sub|super)*type."""
                return self._value
                
        def isEquivalentType(self,otherType):
                """Type equivalence method. Two types are considered equivalent if they
                share the same class and have have equal values."""
                return type(self) == type(otherType) and self._value == otherType.getValue()
                
        def isCustomType(self):
                """Checks whether a type is a user-defined custom type, which must be a string."""
                return type(self._value) is str
                
        def isChild(self,child):
                """This class is a leaf node. It has no children."""
                return False
                
        def getTraversalSuccessors(self):
                """This class is a leaf node. It has no children."""
                return []
        
        def unparseToString(self):
                if type(self._value) is str:
                        return self._value
                else:
                        return self._value.value

class MgType(MgAbstractType):
        """This node represents Magic types, such as Creature or Sorcery."""
        class TypeEnum(Enum):
                Artifact = "artifact"
                Conspiracy = "conspiracy"
                Creature = "creature"
                Enchantment = "enchantment"
                Instant = "instant"
                Land = "land"
                Phenomenon = "phenomenon"
                Plane = "plane"
                Planeswalker = "planeswalker"
                Scheme = "scheme"
                Sorcery = "sorcery"
                Tribal = "tribal"
                Vanguard = "vanguard"

        def __init__(self,value):
                self._traversable = True
                self._value = value
                
        def isPermanentType(self):
                """Checks whether the given type is a recognized permanent type."""
                return self._value in {MgType.TypeEnum.Artifact, MgType.TypeEnum.Creature, MgType.TypeEnum.Enchantment, MgType.TypeEnum.Land, MgType.TypeEnum.Planeswalker}
                
        def isSupplementaryType(self):
                """Checks whether a type is one used in supplemental products like Planechase or Conspiracy."""
                return self._value in {MgType.TypeEnum.Conspiracy,MgType.TypeEnum.Phenomenon,MgType.TypeEnum.Plane,MgType.TypeEnum.Scheme,MgType.TypeEnum.Vanguard}
                
        def isInstantOrSorceryType(self):
                """Checks whether a type is an instant or sorcery."""
                return self._value in {MgType.TypeEnum.Instant,MgType.TypeEnum.Sorcery}
    
class MgSubtype(MgAbstractType):
        """This class represents Magic subtypes, such as Arcane or Elephant."""
        class SpellSubtypeEnum(Enum):
                """Instants and sorceries share their lists of subtypes; these subtypes are called spell types."""
                Arcane = "arcane"
                Trap = "trap"
        
        class LandSubtypeEnum(Enum):
                """Lands have their own unique set of subtypes; these subtypes are called land types."""
                Desert = "desert"
                Forest = "forest"
                Gate = "gate"
                Island = "island"
                Lair = "lair"
                Locus = "locus"
                Mine = "mine"
                Mountain = "mountain"
                Plains = "plains"
                PowerPlant = "power-plant"
                Swamp = "swamp"
                Tower = "tower"
                Urzas = "urza's"
                
        class ArtifactSubtypeEnum(Enum):
                """Artifacts have their own unique set of subtypes; these subtypes are called artifact types."""
                Clue = "clue"
                Contraption = "contraption"
                Equipment = "equipment"
                Fortification = "fortification"
                Treasure = "treasure"
                Vehicle = "vehicle"
                
        class EnchantmentSubtypeEnum(Enum):
                """Enchantments have their own unique set of subtypes; these subtypes are called enchantment types."""
                Aura = "aura"
                Cartouche = "cartouche"
                Curse = "curse"
                Saga = "saga"
                Shrine = "shrine"
        
        class PlaneswalkerSubtypeEnum(Enum):
                """Planeswalkers have their own unique set of subtypes; these subtypes are called planeswalker types."""
                Ajani = "ajani"
                Aminatou = "aminatou"
                Angrath = "angrath"
                Arlinn = "arlinn"
                Ashiok = "ashiok"
                Bolas = "bolas"
                Chandra = "chandra"
                Dack = "dack"
                Daretti = "daretti"
                Domri = "domri"
                Dovin = "dovin"
                Elspeth = "elspeth"
                Estrid = "estrid"
                Freyalise = "freyalise"
                Garruk = "garruk"
                Gideon = "gideon"
                Huatli = "huatli"
                Jace = "jace"
                Jaya = "jaya"
                Karn = "karn"
                Kaya = "kaya"
                Kiora = "kiora"
                Koth = "koth"
                Liliana = "liliana"
                Nahiri = "nahiri"
                Narset = "narset"
                Nissa = "nissa"
                Nixilis = "nixilis"
                Ral = "ral"
                Rowan = "rowan"
                Saheeli = "saheeli"
                Samut = "samut"
                Sarkhan = "sarkhan"
                Sorin = "sorin"
                Tamiyo = "tamiyo"
                Teferi = "teferi"
                Tezzeret = "tezzeret"
                Tibalt = "tibalt"
                Ugin = "ugin"
                Venser = "venser"
                Vivien = "vivien"
                Vraska = "vraska"
                Will = "will"
                Windgrace = "windgrace"
                Xenagos = "xenagos"
                Yanggu = "yanggu"
                Yanling = "yanling"
                
        class CreatureSubtypeEnum(Enum):
                """Creatures and tribals share their lists of subtypes; these subtypes are called creature types."""
                Advisor = "advisor"
                Aetherborn = "aetherborn"
                Ally = "ally"
                Angel = "angel"
                Antelope = "antelope"
                Ape = "ape"
                Archer = "archer"
                Archon = "archon"
                Artificer = "artificer"
                Assassin = "assassin"
                AssemblyWorker = "assembly-worker"
                Atog = "atog"
                Aurochs = "aurochs"
                Avatar = "avatar"
                Azra = "azra"
                Badger = "badger"
                Barbarian = "barbarian"
                Basilisk = "basilisk"
                Bat = "bat"
                Bear = "bear"
                Beast = "beast"
                Beeble = "beeble"
                Berserker = "berserker"
                Bird = "bird"
                Blinkmoth = "blinkmoth"
                Boar = "boar"
                Bringer = "bringer"
                Brushwagg = "brushwagg"
                Camarid = "camarid"
                Camel = "camel"
                Caribou = "caribou"
                Carrier = "carrier"
                Cat = "cat"
                Centaur = "centaur"
                Cephalid = "cephalid"
                Chimera = "chimera"
                Citizen = "citizen"
                Cleric = "cleric"
                Cockatrice = "cockatrice"
                Construct = "construct"
                Coward = "coward"
                Crab = "crab"
                Crocodile = "crocodile"
                Cyclops = "cyclops"
                Dauthi = "dauthi"
                Demon = "demon"
                Deserter = "deserter"
                Devil = "devil"
                Dinosaur = "dinosaur"
                Djinn = "djinn"
                Dragon = "dragon"
                Drake = "drake"
                Dreadnought = "dreadnought"
                Drone = "drone"
                Druid = "druid"
                Dryad = "dryad"
                Dwarf = "dwarf"
                Efreet = "efreet"
                Egg = "egg"
                Elder = "elder"
                Eldrazi = "eldrazi"
                Elemental = "elemental"
                Elephant = "elephant"
                Elf = "elf"
                Elk = "elk"
                Eye = "eye"
                Faerie = "faerie"
                Ferret = "ferret"
                Fish = "fish"
                Flagbearer = "flagbearer"
                Fox = "fox"
                Frog = "frog"
                Fungus = "fungus"
                Gargoyle = "gargoyle"
                Germ = "germ"
                Giant = "giant"
                Gnome = "gnome"
                Goat = "goat"
                Goblin = "goblin"
                God = "god"
                Golem = "golem"
                Gorgon = "gorgon"
                Graveborn = "graveborn"
                Gremlin = "gremlin"
                Griffin = "griffin"
                Hag = "hag"
                Harpy = "harpy"
                Hellion = "hellion"
                Hippo = "hippo"
                Hippogriff = "hippogriff"
                Homarid = "homarid"
                Homunculus = "homunculus"
                Horror = "horror"
                Horse = "horse"
                Hound = "hound"
                Human = "human"
                Hydra = "hydra"
                Hyena = "hyena"
                Illusion = "illusion"
                Imp = "imp"
                Incarnation = "incarnation"
                Insect = "insect"
                Jackal = "jackal"
                Jellyfish = "jellyfish"
                Juggernaut = "juggernaut"
                Kavu = "kavu"
                Kirin = "kirin"
                Kithkin = "kithkin"
                Knight = "knight"
                Kobold = "kobold"
                Kor = "kor"
                Kraken = "kraken"
                Lamia = "lamia"
                Lammasu = "lammasu"
                Leech = "leech"
                Leviathan = "leviathan"
                Lhurgoyf = "lhurgoyf"
                Licid = "licid"
                Lizard = "lizard"
                Manticore = "manticore"
                Masticore = "masticore"
                Mercenary = "mercenary"
                Merfolk = "merfolk"
                Metathran = "metathran"
                Minion = "minion"
                Minotaur = "minotaur"
                Mole = "mole"
                Monger = "monger"
                Mongoose = "mongoose"
                Monk = "monk"
                Monkey = "monkey"
                Moonfolk = "moonfolk"
                Mutant = "mutant"
                Myr = "myr"
                Mystic = "mystic"
                Naga = "naga"
                Nautilus = "nautilus"
                Nephilim = "nephilim"
                Nightmare = "nightmare"
                Nightstalker = "nightstalker"
                Ninja = "ninja"
                Noggle = "noggle"
                Nomad = "nomad"
                Nymph = "nymph"
                Octopus = "octopus"
                Ogre = "ogre"
                Ooze = "ooze"
                Orb = "orb"
                Orc = "orc"
                Orgg = "orgg"
                Ouphe = "ouphe"
                Ox = "ox"
                Oyster = "oyster"
                Pangolin = "pangolin"
                Pegasus = "pegasus"
                Pentavite = "pentavite"
                Pest = "pest"
                Phelddagrif = "phelddagrif"
                Phoenix = "phoenix"
                Pilot = "pilot"
                Pincher = "pincher"
                Pirate = "pirate"
                Plant = "plant"
                Praetor = "praetor"
                Prism = "prism"
                Processor = "processor"
                Rabbit = "rabbit"
                Rat = "rat"
                Rebel = "rebel"
                Reflection = "reflection"
                Rhino = "rhino"
                Rigger = "rigger"
                Rogue = "rogue"
                Sable = "sable"
                Salamander = "salamander"
                Samurai = "samurai"
                Sand = "sand"
                Saproling = "saproling"
                Satyr = "satyr"
                Scarecrow = "scarecrow"
                Scion = "scion"
                Scorpion = "scorpion"
                Scout = "scout"
                Serf = "serf"
                Serpent = "serpent"
                Servo = "servo"
                Shade = "shade"
                Shaman = "shaman"
                Shapeshifter = "shapeshifter"
                Sheep = "sheep"
                Siren = "siren"
                Skeleton = "skeleton"
                Slith = "slith"
                Sliver = "sliver"
                Slug = "slug"
                Snake = "snake"
                Soldier = "soldier"
                Soltari = "soltari"
                Spawn = "spawn"
                Specter = "specter"
                Spellshaper = "spellshaper"
                Sphinx = "sphinx"
                Spider = "spider"
                Spike = "spike"
                Spirit = "spirit"
                Splinter = "splinter"
                Sponge = "sponge"
                Squid = "squid"
                Squirrel = "squirrel"
                Starfish = "starfish"
                Surrakar = "surrakar"
                Survivor = "survivor"
                Tetravite = "tetravite"
                Thalakos = "thalakos"
                Thopter = "thopter"
                Thrull = "thrull"
                Treefolk = "treefolk"
                Trilobite = "trilobite"
                Triskelavite = "triskelavite"
                Troll = "troll"
                Turtle = "turtle"
                Unicorn = "unicorn"
                Vampire = "vampire"
                Vedalken = "vedalken"
                Viashino = "viashino"
                Volver = "volver"
                Wall = "wall"
                Warrior = "warrior"
                Weird = "weird"
                Werewolf = "werewolf"
                Whale = "whale"
                Wizard = "wizard"
                Wolf = "wolf"
                Wolverine = "wolverine"
                Wombat = "wombat"
                Worm = "worm"
                Wraith = "wraith"
                Wurm = "wurm"
                Yeti = "yeti"
                Zombie = "zombie"
                Zubera = "zubera"
                
        class PlanarSubtypeEnum(Enum):
                """Planes have their own unique set of subtypes; these subtypes are called planar types."""
                Alara = "alara"
                Arkhos = "arkhos"
                Azgol = "azgol"
                Belenon = "belenon"
                BolassMeditationRealm = "bolas’s meditation realm"
                Dominaria = "dominaria"
                Equilor = "equilor"
                Ergamon = "ergamon"
                Fabacin = "fabacin"
                Innistrad = "innistrad"
                Iquatana = "iquatana"
                Ir = "ir"
                Kaldheim = "kaldheim"
                Kamigawa = "kamigawa"
                Karsus = "karsus"
                Kephalai = "kephalai"
                Kinshala = "kinshala"
                Kolbahan = "kolbahan"
                Kyneth = "kyneth"
                Lorwyn = "lorwyn"
                Luvion = "luvion"
                Mercadia = "mercadia"
                Mirrodin = "mirrodin"
                Moag = "moag"
                Mongseng = "mongseng"
                Muraganda = "muraganda"
                NewPhyrexia = "new phyrexia"
                Phyrexia = "phyrexia"
                Pyrulea = "pyrulea"
                Rabiah = "rabiah"
                Rath = "rath"
                Ravnica = "ravnica"
                Regatha = "regatha"
                Segovia = "segovia"
                SerrasRealm = "serra’s realm"
                Shadowmoor = "shadowmoor"
                Shandalar = "shandalar"
                Ulgrotha = "ulgrotha"
                Valla = "valla"
                Vryn = "vryn"
                Wildfire = "wildfire"
                Xerex = "xerex"
                Zendikar = "zendikar"
        
        def __init__(self,value):
                self._traversable = True
                self._value = value

        def isSpellSubtype(self):
                return type(self._value) is MgSubtype.SpellSubtypeEnum

        def isArtifactSubtype(self):
                return type(self._value) is MgSubtype.ArtifactSubtypeEnum

        def isLandSubtype(self):
                return type(self._value) is MgSubtype.LandSubtypeEnum

        def isEnchantmentSubtype(self):
                return type(self._value) is MgSubtype.EnchantmentSubtypeEnum

        def isPlaneswalkerSubtype(self):
                return type(self._value) is MgSubtype.PlaneswalkerSubtypeEnum

        def isCreatureSubtype(self):
                return type(self._value) is MgSubtype.CreatureSubtypeEnum

        def isPlanarSubtype(self):
                return type(self._value) is MgSubtype.PlanarSubtypeEnum

class MgSupertype(MgAbstractType):
        """This class represents Magic supertypes, such as Snow or World."""
        class SupertypeEnum(Enum):
                Basic = "basic"
                Legendary = "legendary"
                Ongoing = "ongoing"
                Snow = "snow"
                World = "world"

        def __init__(self,value):
                self._traversable = True
                self._value = value