//A regular declaration introduces something that the card relates to or acts on.
//Example(s): "destroy *target nonblack creature*" and "draw *a card*"
//A reference points to a declaration that was made earlier or that is already assumed to exist.
//Example(s) : "draw a card if *that creature* had power 3 or greater" or "target creature blocks *this turn* if able"
declaration: singledeclaration | compounddeclaration
compounddeclaration:  singledeclaration ("," singledeclaration ",")* "or" singledeclaration -> orcompounddeclaration
| singledeclaration ("," singledeclaration ",")* "and" singledeclaration -> andcompounddeclaration
| singledeclaration ("," singledeclaration ",")* "and/or" singledeclaration -> andorcompounddeclaration
| "neither" singledeclaration "nor" singledeclaration -> neithernorcompounddeclaration
singledeclaration: regulardeclaration | referencedeclaration | keywordabilitydeclaration
regulardeclaration: declarationdecorator* declarationdefinition
referencedeclaration: referencedecorator+ declarationdefinition | personalthirdpersonreferencedefinition | namereferencedefinition

//Reference definition for third-person personal pronoun references.
//Example(s): "*they* can’t be regenerated." and "Sarkhan the Mad deals damage to *himself*"
personalthirdpersonreferencedefinition: THIRDPERSONPERSONALREFERENCE | SELFPRONOUNREFERENCE | HERAMBIGUOUSREFERENCE
HERAMBIGUOUSREFERENCE.100: "her" //This could be the possessive form or the object of a sentence.
THIRDPERSONPERSONALREFERENCE.90: ("he" | "him") | ("she") | ("they" | "them") | "it"
SELFPRONOUNREFERENCE.110:  "itself" | "himself" | "herself" | "themselves"

//Reference form used when when a card makes a reference to itself by name. "~" is a full name reference, "~f" (rarely used) is a first name reference.
//Example(s): "*Chandra, Fire of Kaladesh (~)* deals 1 damage to target player or planeswalker. If *Chandra (~f)* has dealt 3 or more damage [...]"
namereferencedefinition: NAMEREFSYMBOL
NAMEREFSYMBOL: "~" | "~f"

//Reference decorators help clarify what is being talked about. Note that reference decorators can have nested
//references to other defined things (like "your *opponent's* hand").
//Example(s): "Destroy target creature. *Its* controller [...]" and "*its owner’s* hand." "*that creature’s* toughness."
referencedecorator: THIRDPERSONIMPERSONALREFERENCE | POSSESSIVEPRONOUNREFERNCE | HERAMBIGUOUSREFERENCE
THIRDPERSONIMPERSONALREFERENCE: ("that" | "those") | ("this"|"these")
POSSESSIVEPRONOUNREFERNCE.100: "its" | "your" | "their" | "his" //Note: "her" is handled separately to capture the ambiguity.

//Declaration decorators. The most popular decorator is "target".
//Example(s): "destroy *target* nonblack creature", "*any* permanent"
declarationdecorator: "each" -> eachdecorator
| "same" -> samedecorator
| "all" -> alldecorator
| ["an"]"other" -> otherdecorator
| ("a" | "an") -> indefinitearticledecorator
| "the" -> definitearticledecorator
| valueterm? "target" -> targetdecorator
| "any" -> anydecorator

//A declaration definition is made up of a set of descriptive terms like "a *blue permanent*" or "*two 1/1 green elf creature tokens*".
//There can be limited nesting of declarations inside definitions like with possessives ("its *owner's* hand") and prepositions
//("a creature *with a +1/+1 counter* *on it*").
declarationdefinition: "DEFINITION" | (nonnesteddeclarationterm | nesteddeclarationterm)+ //TODO: Remove "DEFINITION" placeholder
nonnesteddeclarationterm : ("non""-"?)? (valueterm | manaterm | characteristicterm
| typeterm | colorterm | modifierterm | qualifierterm | timeterm | damageterm | playerterm
| powertoughnessterm | loyaltycostterm | counterterm | nameterm | variableterm | zoneterm | anytargetterm )
nesteddeclarationterm: possessiveclarationreference | prepositionalattacheddeclaration

//Declaration definitions can have prepositional phrases and possessives that can contain declarations of their own.
//We need a special rule for embedded declarations which shouldn't have any further recursive declarations. Instead,
//we treat the declaration as flat and it's the job of a semantic analyzer to determine how they are really nested.
//For example, we parse "the owner of the creature with a +1/+1 counter on it" as
//"the owner (of the creature) (with a +1/+1 counter) (on it)" rather than
//"the owner (of the creature (with a +1/+1 counter (on it)))", if that makes sense.
embeddedsingledeclaration: embeddedregulardeclaration | embeddedreferencedeclaration
embeddedregulardeclaration: declarationdecorator* embeddeddeclarationdefinition
embeddedreferencedeclaration: referencedecorator+ embeddeddeclarationdefinition | personalthirdpersonreferencedefinition | namereferencedefinition
embeddeddeclarationdefinition: nonnesteddeclarationterm+
prepositionalattacheddeclaration: DECLARATIONPREPOSITION embeddedsingledeclaration
DECLARATIONPREPOSITION: "of" | ("on" | "onto") | "who" | "in" | "under" | "with"
possessiveclarationreference: (embeddeddeclarationdefinition | namereferencedefinition) ("'s"|"'")



typeterm: (TYPE ["s"] | SUBTYPESPELL ["s"] | SUBTYPELAND ["s"] | SUBTYPEARTIFACT ["s"] | SUBTYPEENCHANTMENT ["s"] | SUBTYPEPLANESWALKER | SUBTYPECREATUREA ["s"] | SUBTYPECREATUREB ["s"] | SUBTYPEPLANAR | SUPERTYPE)
modifierterm: ABILITYMODIFIER | COMBATSTATUSMODIFIER | KEYWORDSTATUSMODIFIER | TAPPEDSTATUSMODIFIER | EFFECTSTATUSMODIFIER | RELATIVEMODIFIER
qualifierterm: QUALIFIER["s"]
timeterm: PHASE | STEP | TURN | GAME
playerterm: PLAYER["s"]
zoneterm: ZONE
powertoughnessterm: valueterm "/" valueterm
loyaltycostterm: "[" (PLUS | PWMINUS)? valueterm "]"
counterterm: (COUNTERTYPE | powertoughnessterm)  "counter"["s"]
characteristicterm: OBJECTCHARACTERISTIC | PLAYERCHARACTERISTIC
nameterm: "OBJECTNAME" | NAMEREFSYMBOL //TODO: fix objectname vs. basic lexer
damageterm: DAMAGETYPE
colorterm: COLOR
variableterm: "choice"["s"] //Example(s): "their choice", "of your choice"
| ("copy" | "copies") //Example(s): "You may have Shapeshifters you control become *copies* of that creature", "choose new targets for the *copy*"
| "vote"["s"] //Example(s): "each *vote* they receive"
| NUMBERPROPERTY? "number"["s"] //Example(s): "the *number* of cards you drew this term", "a *prime number* of lands"
| "time"["s"] //Example(s): "the number of *times* ~ was kicked", "the first time this turn"
anytargetterm: "any target" //Special nullary variant like "~ deals three damage to *any target*"


//Keyworded ability declaration
//Regular keyworded abilities are those that are of the form "keyword (cost/description"?.
//Note that the parser will allow for illegal keyworded ability definitions like "flying 3", and it's the
//job of the semantic analyzer to check for things like this. Special keyworded abilities, meanwhile, are
//those that have very particular syntax around them and its easier to spell them out in a special rule.
keywordabilitydeclaration: regularkeywordedabilitydefinition | specialkeywordedabilitydefinition

regularkeywordedabilitydefinition: REGULARKEYWORDEDABILITY declaration? //Example(s): "Flying", "Bushido 3", "Champion a Kithkin"
| REGULARKEYWORDEDABILITY declaration DASH declaration //Example(s): "Impending 4—{2}{R}{R}"

specialkeywordedabilitydefinition: "specialkeywordedabilitydefinition" //TODO

//need to handle past tense of keyworded actions like "kicked" or "plotted" as part of declarations
//special cases include...
//landwalk, hexproof from X and from Y, [typeexpression] "cycling" cost, "splice" "onto" typeexpression cost, typeexpression "offering"
//"forecast" activationstatement, "suspend" valuenumber cost, "aura swap" (if we wanted to generalize to TYPE swap)
//partner with objectname, kwcompanion: "companion", "craft" "with" declarationorreference cost, spree (Choose one or more additional costs.)

REGULARKEYWORDEDABILITY: "deathtouch" | "defender" | "double strike" | "enchant" | "equip" | "first strike" | "flash" | "flying"
| "haste" | "indestructible" | "intimidate" | "lifelink" | "reach" | "shroud" | "trample" | "vigilance" | "ward" | "rampage"
| "cumulative upkeep" | "flanking" | "phasing" | "buyback" | "shadow" | "echo" | "horsemanship" | "fading" | "multi"? "kicker"
| "flashback" | "madness" | "fear" | "mega"? "morph" | "amplify" | "provoke" | "storm" | "affinity" "for"? | "entwine" | "modular"
| "sunburst" | "bushido" | "soulshift" | "ninjutsu" | "epic" | "convoke" | "dredge" | "transmute" | "bloodthirst" | "haunt"
| "graft" | "recover" | "ripple" | "split second" | "suspend" | "vanishing" | "absorb" | "aura swap" | "delve" | "delve"
| "fortify" | "frenzy" | "gravestorm" | "poisonous" | "transfigure" | "champion" | "changeling" | "evoke" | "hideaway" | "prowl"
| "reinforce" | "conspire" | "persist" | "wither" | "retrace" | "devour" | "exalted" | "unearth" | "cascade" | "annihilator"
| "level up" | "rebound" | "totem armor" | "infect" | "battle cry" | "living weapon" | "undying" | "miracle" | "soulbond"
| "overload" | "scavenge" | "unleash" | "cipher" | "evolve" | "extort" | "fuse" | "bestow" | "tribute" | "dethrone"
| "hidden agenda" | "outlast" | "prowess" | "dash" | "exploit" | "menace" | "renown" | "awaken" | "devoid" | "ingest"
| "myriad" | "surge" | "skulk" | "emerge" | "escalate" | "melee" | "crew" | "fabricate" | "undaunted" | "improvise" | "aftermath"
| "embalm" | "eternalize" | "afflict" | "ascend" | "assist" | "jump-start" | "mentor" | "afterlife" | "riot" | "spectacle"
| "escape" | "mutate" | "oncore" | "boast" | "foretell" | "demonstrate" | ("day" | "night") "bound" | "disturb" | "decayed"
| "cleave" | "training" | " compleated" | "reconfigure" | "blitz" | "casualty" | "enlist" | "read ahead" | "ravenous" | "squad"
| "prototype" | "living metal" | "for mirrodin!" | "toxic" | "backup" | "bargain" | "disguise" | "plot" | "saddle"
| "gift" | "offspring" | "impending"


//Below are hardcoded game terms used in declarations.
PLAYER: "player" | "opponent" | "you" |  "teammate" | "team" | "controller" | "owner"
PLAYERCHARACTERISTIC: "maximum hand size" | "life total"["s"] | "life" | "cards in hand"
OBJECTCHARACTERISTIC: "card"? "name" | "mana value" | "color"["s"] | "color indicator" | "type"["s"] | "card type"["s"] | "subtype"["s"] | "supertype"["s"]
| "rules text" | ("ability" | "abilities" ) | "power" | "toughness" | "base power" | "base toughness" | "loyalty" | "hand modifier" | "life modifier"
ZONE: "battlefield" | "graveyard"["s"] | ("library"|"libraries") | "hand"["s"] | "stack" | "exile" | "command zone" | "outside the game" | "anywhere"
TYPE.100: "planeswalker" | "conspiracy" | "creature" | "enchantment" | "instant" | "land" | "phenomenon" | "plane" | "artifact" | "scheme" | "sorcery" | "tribal" | "vanguard"
SUBTYPESPELL : "arcane" | "trap" | "adventure"
SUBTYPELAND: "desert" | "forest" | "gate" | "island" | "lair" | "locus"
| "mine" | "mountain" | "plains" | "power-plant" | "swamp" | "tower" | "urza's"
SUBTYPEARTIFACT: "clue" | "contraption" | "equipment" | "fortification" | "treasure" | "vehicle" | "food"
SUBTYPEENCHANTMENT: "aura" | "cartouche" | "curse" | "saga" | "shrine" | "rune" | "shard" | "case" | "room"
SUBTYPEPLANESWALKER: "ajani" | "aminatou" | "angrath" | "arlinn" | "ashiok" | "bolas" | "chandra"
| "dack" | "daretti" | "domri" | "dovin" | "elspeth" | "estrid" | "freyalise" | "garruk" | "gideon"
| "huatli" | "jace" | "jaya" | "karn" | "kaya" | "kiora" | "koth" | "liliana" | "nahiri" | "narset"
| "nissa" | "nixilis" | "ral" | "rowan" | "saheeli" | "samut" | "sarkhan" | "sorin" | "tamiyo" | "teferi"
| "tezzeret" | "tibalt" | "ugin" | "venser" | "vivien" | "vraska" | "will" | "windgrace" | "xenagos"
| "yanggu" | "yanling"
//[TODO: SUBTYPECREATUREA and SUBTYPECREATUREB are split up because having such a long list of alternatives apparently]
//[causes Lark to suffer a recursion depth error. We should see if this is fixable.]
SUBTYPECREATUREA: "advisor" | "aetherborn" | ("ally"|"allies") | "angel" | "antelope" | "ape" | "archer" | "archon"
| "artificer" | "assassin" | "assembly-worker" | "atog" | "aurochs" | "avatar" | "azra" | "badger"
| "barbarian" | "basilisk" | "bat" | "bear" | "beast" | "beeble" | "berserker" | "bird" | "blinkmoth"
| "boar" | "bringer" | "brushwagg" | "camarid" | "camel" | "caribou" | "carrier" | "cat" | "centaur"
| "cephalid" | "chimera" | "citizen" | "cleric" | "cockatrice" | "construct" | "coward" | "crab"
| "crocodile" | "cyclops" | "dauthi" | "demon" | "deserter" | "detective" | "devil" | "dinosaur" | "djinn" | "dragon"
| "drake" | "dreadnought" | "drone" | "druid" | "dryad" | ("dwarf"|"dwarves") | "efreet" | "egg" | "elder" | "eldrazi"
| "elemental" | "elephant" | ("elf"|"elves") | "elk" | "eye" | "faerie" | "ferret" | "fish" | "flagbearer" | "fox"
SUBTYPECREATUREB: "frog" | "fungus" | "gargoyle" | "germ" | "giant" | "gnome" | "goat" | "goblin" | "god" | "golem" | "gorgon"
| "graveborn" | "gremlin" | "griffin" | "hag" | "harpy" | "hellion" | "hippo" | "hippogriff" | "homarid" | "homunculus"
| "horror" | "horse" | "hound" | "human" | "hydra" | "hyena" | "illusion" | "imp" | "incarnation" | "insect"
| "jackal" | "jellyfish" | "juggernaut" | "kavu" | "kirin" | "kithkin" | "knight" | "kobold" | "kor" | "kraken"
| "lamia" | "lammasu" | "leech" | "leviathan" | "lhurgoyf" | "licid" | "lizard" | "manticore" | "masticore"
| ("mercenary"|"mercenaries") | "merfolk" | "metathran" | "minion" | "minotaur" | "mole" | "monger" | "mongoose" | "monk"
| "monkey" | "moonfolk" | "mouse" | "mutant" | "myr" | "mystic" | "naga" | "nautilus" | "nephilim" | "nightmare"
| "nightstalker" | "ninja" | "noggle" | "nomad" | "nymph" | ("octopus"|"octopuses") | "ogre" | "ooze" | "orb" | "orc"
| "orgg" | "ouphe" | "ox" | "oyster" | "pangolin" | "pegasus" | "pentavite" | "pest" | "phelddagrif" | "phoenix"
| "pilot" | "pincher" | "pirate" | "plant" | "praetor" | "prism" | "processor" | "rabbit" | "rat" | "rebel"
| "reflection" | "rhino" | "rigger" | "rogue" | "sable" | "salamander" | "samurai" | "sand" | "saproling" | "satyr"
| "scarecrow" | "scion" | "scorpion" | "scout" | "serf" | "serpent" | "servo" | "shade" | "shaman" | "shapeshifter"
| "sheep" | "siren" | "skeleton" | "slith" | "sliver" | "slug" | "snake" | "soldier" | "soltari" | "spawn" | "specter"
| "spellshaper" | "sphinx" | "spider" | "spike" | "spirit" | "splinter" | "sponge" | "squid" | "squirrel" | "starfish"
| "surrakar" | "survivor" | "tetravite" | "thalakos" | "thopter" | "thrull" | "treefolk" | "trilobite" | "triskelavite"
| "troll" | "turtle" | "unicorn" | "vampire" | "vedalken" | "viashino" | "volver" | "wall" | "warrior" | "warlock" | "weird"
| ("werewolf"|"werewolves") | "whale" | "wizard" | ("wolf"|"wolves") | "wolverine" | "wombat" | "worm" | "wraith" | "wurm" | "yeti"
| "zombie" | "zubera"
SUBTYPEPLANAR: "alara" | "arkhos" | "azgol" | "belenon" | "bolas’s meditation realm"
| "dominaria" | "equilor" | "ergamon" | "fabacin" | "innistrad" | "iquatana" | "ir"
| "kaldheim" | "kamigawa" | "karsus" | "kephalai" | "kinshala" | "kolbahan" | "kyneth"
| "lorwyn" | "luvion" | "mercadia" | "mirrodin" | "moag" | "mongseng" | "muraganda"
| "new phyrexia" | "phyrexia" | "pyrulea" | "rabiah" | "rath" | "ravnica" | "regatha"
| "segovia" | "serra’s realm" | "shadowmoor" | "shandalar" | "ulgrotha" | "valla"
| "vryn" | "wildfire" | "xerex" | "zendikar"
subtype: SUBTYPESPELL | SUBTYPELAND | SUBTYPEARTIFACT | SUBTYPEENCHANTMENT | SUBTYPEPLANESWALKER | SUBTYPECREATUREA | SUBTYPECREATUREB | SUBTYPEPLANAR
SUPERTYPE: "basic" | "legendary" | "ongoing" | "snow" | "world"
DAMAGETYPE: "damage" | "combat damage" | "excess damage"
ABILITYMODIFIER: "triggered" | "activated" | "mana" | "loyalty"
RELATIVEMODIFIER: "next" | "additional" | "extra" //Example(s): "an *additional* +1/+1 counter", "take an *extra* turn"
COMBATSTATUSMODIFIER: "attacking" | "defending" | "attacked" | "blocking" | "blocked" | "active" //Example(s): "the *active* player", "*attacking* creatures you control"
KEYWORDSTATUSMODIFIER: "paired" | "kicked" | "face-up" | "face-down" | "transformed" | "enchanted" | "equipped" //TODO: This will need to be generalized more.
| "fortified" | "monstrous" | "regenerated" | "suspended" | "flipped" | "suspected" // TODO: ensure 'suspected' works properly
TAPPEDSTATUSMODIFIER: ["un"]"tapped"
EFFECTSTATUSMODIFIER: "named" | "chosen" | "chosen at random" | "revealed" | "returned" | "destroyed" | "exiled" | "died" | "countered" | "sacrificed"
| "prevented" | "created"
QUALIFIER: "card" | "permanent" | "source" | "spell" | "token" | "effect"
COLOR: "white" | "blue" | "black" | "red" | "green" | "monocolored" | "multicolored" | "colorless"
PHASE: "beginning phase" | ("precombat" | "postcombat")? "main phase" | ("combat" | "combat phase") | "ending phase"
STEP: "untap step" | ("upkeep step" | "upkeep") | "draw step" | "beginning of combat" | "declare attackers step"
| "declare blockers step" | "combat damage step" | "end of combat" | "end step" | "cleanup step" | "step"
TURN: "turn"
GAME: "game"

//TODO: counter types aren't formally defined in the game (like the "oil" counters doesn't have a specific rules meaning, but until we
//can have arbitrary names that don't confuse the basic lexer, we might spell out counter types here based on the list
//provided here: https://mtg.fandom.com/wiki/Counter_(marker)/Full_List.
COUNTERTYPE: "COUNTERTYPE" //TODO

//COUNTERTYPE: "aegis" | "age" | "aim" | "arrow" | "arrowhead" | "awakening" | "bait" | "blaze" | "blessing" | "blight" | "blood" | "bloodline"
//| "bloodstain" | "book" | "bounty" | "brain" | "bribery" | "brick" | "burden" | "cage" | "carrion" | "charge" | "coin" | "collection" | "component"
//| "contested" | "corruption" | "crank!" | "credit" | "croak" | "corpse" | "crystal" | "cube" | "currency" | "death" | "defense" | "delay"
//| "depletion" | "descent" | "despair" | "devotion" | "discovery" | "divinity" | "doom" | "dream" | "echo

//Rules for mana symbols
//TODO: Add in text mana descriptions here
manaterm: manasymbol
manasymbol: "{" manamarkerseq "}"
manamarkerseq: manamarker_color -> regularmanasymbol
| NUMBER -> genericmanasymbol
| manamarker_halfmana manamarker_color -> halfmanasymbol
| manamarker_color "/" manamarker_phyrexian -> phyrexianmanasymbol
| manamarker_color "/" manamarker_color -> hybridmanasymbol
| NUMBER "/" manamarker_color -> alternate2manasymbol
| manamarker_snow -> snowmanasymbol
| manamarker_colorless -> colorlessmanasymbol
| manamarker_x -> xmanasymbol
manamarker_halfmana: "H"i -> halfmarker
manamarker_color: "W"i -> whitemarker
| "U"i -> bluemarker
| "B"i -> blackmarker
| "R"i -> redmarker
| "G"i -> greenmarker
manamarker_snow: "S"i -> snowmarker
manamarker_phyrexian: "P"i -> phyrexianmarker
manamarker_colorless: "C"i -> colorlessmarker
manamarker_x: "X"i -> xmarker

//Rules for representing numeric values and math operations
valueterm: NUMBER  | CARDINAL ("time"["s"])?| ORDINAL | FREQUENCY | VARIABLEVALUE | valueoperation
FREQUENCY: "once" | "twice"
CARDINAL: "one" | "two" | "three" | "four" | "five" | "six" | "seven" | "eight" | "nine" | "ten"
| "eleven" | "twelve" | "thirteen" | "fourteen" | "fifteen" | "sixteen" | "seventeen" | "eighteen" | "nineteen" | "twenty" //[TODO]
ORDINAL: "first" | "second" | "third" | "fourth" | "fifth" | "sixth" | "seventh" | "eighth" | "ninth" | "tenth" //[TODO]
VARIABLEVALUE: "x" | "*"
NUMBERPROPERTY: "odd" | "even" | "prime"

//[NOTE: Both Scryfall and Mtgjson use a long dash, not a short dash, to indicate a minus on a planeswalker ability]
PWMINUS: "−"
PLUS: "+"
MINUS: "-"

tapuntapsymbol: TAPSYMBOL | UNTAPSYMBOL
TAPSYMBOL: "{T}"i
UNTAPSYMBOL: "{Q}"i

valueoperation: valuecomparisonoperation | valuemathoperation
valuecomparisonoperation: "equal to" valueterm // ==
    | "less than" "or equal to"? valueterm // < ; <=
    | "greater than" "or equal to"? valueterm // > ; >=
    | "up to" valueterm // <=
    | valueterm "or" ("less" | "fewer") // <=
    | valueterm "or" ("greater" | "more") // >=
valuemathoperation: ("that much" | "that many") //Example: "create *that many* treasure tokens", "draw twice *that many* cards"
| valueterm "rounded" ("up" | "down")
| valueterm "divided" ("evenly" | "as you choose")
| valueterm "plus" valueterm //Example: "the number of Elves you control *plus* the number of Elf cards in your graveyard."
| valueterm "minus" valueterm //Example: "the number of cards in your hand *minus* the number of cards in that player’s hand."