//Expressions make things happen in the game. When spell states "~ *deals* 3 damage to target creature", "nonbasic lands *are* mountains",
//or "target player *loses* the game", damage is dealt, lands become mountains, and a player loses the game. Expressions take declarations
//or other expressions (like who deals the damage and to whom is the damage dealt). Meanwhile, statements can contain expressions, like the
//if statement "if you control a modified creature, draw a card" is equivalent to (if the expression "you control a modified creature" evaluates
//to true, make the expression "draw a card" happen.

expression.5: simpleverbexpression | reservedverbexpression | mathexpression
expressionordeclaration.5: expression | declaration


mathexpression.5: mathcomparisonexpression | mathoperationexpression
mathcomparisonexpression.5: expressionordeclaration "equal"i PREPOSITION_TO expressionordeclaration // ==
    | expressionordeclaration? "less"i "than"i (CONJUNCTION_OR "equal"i PREPOSITION_TO)? expressionordeclaration // < ; <=
    | expressionordeclaration? ("greater"i | "more"i) "than" ("or equal"i PREPOSITION_TO)? expressionordeclaration // > ; >=
    | expressionordeclaration? "up"i PREPOSITION_TO expressionordeclaration // <=
    | expressionordeclaration CONJUNCTION_OR ("less"i | "fewer"i) // <=
    | expressionordeclaration CONJUNCTION_OR ("greater"i | "more"i) // >=
    | expressionordeclaration ("less"i | "more"i) //Example(s): "This costs *{1} less* to cast"
mathoperationexpression.5: expressionordeclaration "rounded"i ("up"i | "down"i) //TODO: This is usually read as an adverb like "Heartless Hidetsugu deals damage to each player equal to half that player’s life total, *rounded down*."
| expressionordeclaration MATHOPERATION_PLUS expressionordeclaration //Example: "the number of Elves you control *plus* the number of Elf cards in your graveyard."
| expressionordeclaration MATHOPERATION_MINUS expressionordeclaration //Example: "the number of cards in your hand *minus* the number of cards in that player’s hand."
MATHOPERATION_PLUS.5: "plus"i
MATHOPERATION_MINUS.5: "minus"i

simpleverbexpression.5: expressionordeclaration? ( ((BEPRESENT | BEPAST | BEFUTURESUBJUNCTIVE) ("not")? expressionordeclaration) | (("not")? (BEPARTICIPLEORGERUND | BEPLAIN) expressionordeclaration) ) -> beexpression
| expressionordeclaration? verb_have ("not")? expressionordeclaration -> haveexpression
| expressionordeclaration? verb_can ("not")? expressionordeclaration -> canexpression
| expressionordeclaration? verb_become expressionordeclaration -> becomeexpression
| expressionordeclaration? (verb_may | verb_must) ("not")? expressionordeclaration -> maymustexpression
| expressionordeclaration? (expressionordeclaration? verb_do ("not")? expressionordeclaration?) -> doexpression

reservedverbexpression.5: reservedverbsubjects reservedverbverb (reservedverbprepositionmodifiers* | reservedverbobject reservedverbmodifiers*) //Example(s): "target player sacrifices a creature"
| reservedverbverb reservedverbobject reservedverbmodifiers* //Example(s): "Destroy target creature"
| reservedverbverb_verbonly //Example(s): "Proliferate", "Populate", "they can not be *attacked*"
reservedverbsubjects.5: singledeclaration | compounddeclaration | singledeclaration pronounonlyreferencedeclaration

reservedverbverb.5: reservedverbadverb? (reservedverb_presentonly | reservedverb_pastonly) reservedverbadverb?
reservedverbverb_verbonly.5: reservedverb_presentonly | reservedverb_pastonly
reservedverbadverb.5: "secretly" //Example(s): "*secretly* choose Human, Merfolk, or Goblin."
| "continuously"i //Example(s): "controlled *continuously* since the beginning of the turn",
| "again"i //Example(s): Whenever you discover, discover *again* for the same value.
| "at random"i //Example(s): "Return a card at random from your graveyard to your hand" //TODO: this doesn't work with Ghoulraiser, adverbs can be placed elsewhere.
| "still"i //Example(s): "It is *still* a land"
| "so"i //Example(s): "While doing *so*, the player can activate mana abilities [...]"
| "evenly"i //Example(s): "Fireball deals X damage divided *evenly*, rounded down, among any number of targets."
reservedverbobject.5: declaration | mathexpression
reservedverbmodifiers.5: reservedverbprepositionmodifiers | reservedverbdeclarationmodifiers | reservedverbexpression //TODO: I put a 'reservedverbexpression' rule here to capture things like "exile target creature *you control*", but is that the right way to do this?
reservedverbprepositionmodifiers.5: expressionpreposition expressionordeclaration //Example(s): "Return target creature card *from your graveyard* *to the battlefield*."
reservedverbdeclarationmodifiers.5: decorateddeclaration //Example(s): "Up to two target creatures can’t block *this turn*."
expressionpreposition.0: ONLY? ( PREPOSITION_AMONG //Example(s): "Distribute two +1/+1 counters *among* one or two target creatures."
| PREPOSITION_FROM //Example(s): "return target creature *from* your graveyard to the battlefield"
| PREPOSITION_INTO //Example(s): "put that card *into* your graveyard"
| PREPOSITION_ONTO //Example(s): "put that card *onto* the battlefield"
| PREPOSITION_TO //Examples(s): "this spell costs {1} less *to* cast for each [...]", "~ deals 3 damage *to* target creature"
| PREPOSITION_OF //Example(s): "gain control *of* target creature"
| PREPOSITION_ON //Example(s): "put a +1/+1 counter *on* target creature you control"
| PREPOSITION_WITH //Example(s): "whenever you attack *with* three or more creatures"
| PREPOSITION_HOW)  //Example(s): "you choose which creatures block this turn and *how* those creatures block"

simpleverb.5: verb_be | verb_have | verb_can | verb_become | verb_may | verb_must | verb_do

reservedverb.10: verb_abandon | verb_activate | verb_adapt | verb_add | verb_amass | verb_assign | verb_attach | verb_attack | verb_block | verb_bolster | verb_cast
| verb_cause | verb_change | verb_choose | verb_clash | verb_cloak | verb_collect | verb_connive | verb_control | verb_copy | verb_counter | verb_create | verb_cycle
| verb_deal | verb_declare | verb_destroy | verb_detain | verb_die | verb_discard | verb_discover | verb_divide | verb_double | verb_draw | verb_enter | verb_enchant
| verb_equip | verb_exchange | verb_exert | verb_exile | verb_explore | verb_fateseal | verb_fight | verb_flip | verb_forage | verb_gain | verb_get | verb_gift
| verb_goad | verb_incubate | verb_investigate | verb_kick | verb_learn | verb_leave | verb_look | verb_lose | verb_name | verb_manifest | verb_meld | verb_mill | verb_multiply | verb_pay
| verb_planeswalk | verb_play | verb_populate | verb_prevent | verb_proliferate | verb_put | verb_regenerate | verb_remain | verb_remove | verb_resolve | verb_return
| verb_roll | verb_reveal | verb_sacrifice | verb_scry | verb_search | verb_setinmotion | verb_separate | verb_share | verb_shuffle | verb_skip | verb_spend | verb_support | verb_surveil
| verb_subtract | verb_suspect | verb_suspend | verb_switch | verb_take | verb_tap | verb_target | verb_tempt | verb_timetravel | verb_transform | verb_trigger | verb_turn | verb_vote | verb_win

reservedverb_presentonly.5: ABANDONPRESENT | ACTIVATEPRESENT | ADAPTPRESENT | ADDPRESENT | AMASSPRESENT | ASSIGNPRESENT | ATTACHPRESENT | ATTACKPRESENT | BLOCKPRESENT | BOLSTERPRESENT | CASTPRESENT
| CAUSEPRESENT | CHANGEPRESENT | CHOOSEPRESENT | CLASHPRESENT | CLOAKPRESENT | COLLECTPRESENT | CONNIVEPRESENT | CONTROLPRESENT | COPYPRESENT | COUNTERPRESENT | CREATEPRESENT | CYCLEPRESENT
| DEALPRESENT | DECLAREPRESENT | DESTROYPRESENT | DETAINPRESENT | DIEPRESENT | DISCARDPRESENT | DISCOVERPRESENT | DIVIDEPRESENT | DOUBLEPRESENT | DRAWPRESENT | ENTERPRESENT | ENCHANTPRESENT
| EQUIPPRESENT | EXCHANGEPRESENT | EXERTPRESENT | EXILEPRESENT | EXPLOREPRESENT | FATESEALPRESENT | FIGHTPRESENT | FLIPPRESENT | FORAGEPRESENT | GAINPRESENT | GETPRESENT | GIFTPRESENT
| GOADPRESENT | INCUBATEPRESENT | INVESTIGATEPRESENT | KICKPRESENT | LEARNPRESENT | LEAVEPRESENT | LOOKPRESENT | LOSEPRESENT | NAMEPRESENT | MANIFESTPRESENT | MELDPRESENT | MILLPRESENT | MULTIPLYPRESENT | PAYPRESENT
| PLANESWALKPRESENT | PLAYPRESENT | POPULATEPRESENT | PREVENTPRESENT | PROLIFERATEPRESENT | PUTPRESENT | REGENERATEPRESENT | REMAINPRESENT | REMOVEPRESENT | RESOLVEPRESENT | RETURNPRESENT
| ROLLPRESENT | REVEALPRESENT | SACRIFICEPRESENT | SCRYPRESENT | SEARCHPRESENT | SETINMOTIONPRESENT | SEPARATEPRESENT | SHAREPRESENT | SHUFFLEPRESENT | SKIPPRESENT | SPENDPRESENT | SUPPORTPRESENT | SURVEILPRESENT
| SUBTRACTPRESENT | SUSPECTPRESENT | SUSPENDPRESENT | SWITCHPRESENT | TAKEPRESENT | TAPPRESENT | TARGETPRESENT | TEMPTPRESENT | TIMETRAVELPRESENT | TRANSFORMPRESENT | TRIGGERPRESENT | TURNPRESENT | VOTEPRESENT | WINPRESENT

reservedverb_pastonly.5: ABANDONPAST | ACTIVATEPAST | ADAPTPAST | ADDPAST | AMASSPAST | ASSIGNPAST | ATTACHPAST | ATTACKPAST | BLOCKPAST | BOLSTERPAST | CASTPAST
| CAUSEPAST | CHANGEPAST | CHOOSEPAST | CLASHPAST | CLOAKPAST | COLLECTPAST | CONNIVEPAST | CONTROLPAST | COPYPAST | COUNTERPAST | CREATEPAST | COSTPRESENT | CYCLEPAST
| DEALPAST | DECLAREPAST | DESTROYPAST | DETAINPAST | DIEPAST | DISCARDPAST | DISCOVERPAST | DIVIDEPAST | DOUBLEPAST | DRAWPAST | ENTERPAST | ENCHANTPAST
| EQUIPPAST | EXCHANGEPAST | EXERTPAST | EXILEPAST | EXPLOREPAST | FATESEALPAST | FIGHTPAST | FLIPPAST | FORAGEPAST | GAINPAST | GETPAST | GIFTPAST
| GOADPAST | INCUBATEPAST | INVESTIGATEPAST | KICKPAST | LEARNPAST | LEAVEPAST | LOOKPAST | LOSEPAST | NAMEPAST | MANIFESTPAST | MELDPAST | MILLPAST | MULTIPLYPAST | PAYPAST
| PLANESWALKPAST | PLAYPAST | POPULATEPAST | PREVENTPAST | PROLIFERATEPAST | PUTPAST | REGENERATEPAST | REMAINPAST | REMOVEPAST | RESOLVEPAST | RETURNPAST
| ROLLPAST | REVEALPAST | SACRIFICEPAST | SCRYPAST | SEARCHPAST | SEPARATEPAST | SHAREPAST | SHUFFLEPAST | SKIPPAST | SPENDPAST | SUPPORTPAST | SURVEILPAST
| SUBTRACTPAST | SUSPECTPAST | SUSPENDPAST | SWITCHPAST | TAKEPAST | TAPPAST | TARGETPAST | TEMPTPAST | TIMETRAVELPAST | TRANSFORMPAST | TRIGGERPAST | TURNPAST | VOTEPAST | WINPAST

reservedverb_participleorgerundonly.5: ABANDONPARTICIPLEORGERUND | ACTIVATEPARTICIPLEORGERUND | ADAPTPARTICIPLEORGERUND | ADDPARTICIPLEORGERUND | AMASSPARTICIPLEORGERUND | ASSIGNPARTICIPLEORGERUND | ATTACHPARTICIPLEORGERUND | ATTACKPARTICIPLEORGERUND | BLOCKPARTICIPLEORGERUND | BOLSTERPARTICIPLEORGERUND | CASTPARTICIPLEORGERUND
| CAUSEPARTICIPLEORGERUND | CHANGEPARTICIPLEORGERUND | CHOOSEPARTICIPLEORGERUND | CLASHPARTICIPLEORGERUND | CLOAKPARTICIPLEORGERUND | COLLECTPARTICIPLEORGERUND | CONNIVEPARTICIPLEORGERUND | CONTROLPARTICIPLEORGERUND | COPYPARTICIPLEORGERUND | COUNTERPARTICIPLEORGERUND | CREATEPARTICIPLEORGERUND | COSTPARTICIPLEORGERUND | CYCLEPARTICIPLEORGERUND
| DEALPARTICIPLEORGERUND | DECLAREPARTICIPLEORGERUND | DESTROYPARTICIPLEORGERUND | DETAINPARTICIPLEORGERUND | DIEPARTICIPLEORGERUND | DISCARDPARTICIPLEORGERUND | DISCOVERPARTICIPLEORGERUND | DIVIDEPARTICIPLEORGERUND | DOUBLEPARTICIPLEORGERUND | DRAWPARTICIPLEORGERUND | ENTERPARTICIPLEORGERUND | ENCHANTPARTICIPLEORGERUND
| EQUIPPARTICIPLEORGERUND | EXCHANGEPARTICIPLEORGERUND | EXERTPARTICIPLEORGERUND | EXILEPARTICIPLEORGERUND | EXPLOREPARTICIPLEORGERUND | FATESEALPARTICIPLEORGERUND | FIGHTPARTICIPLEORGERUND | FLIPPARTICIPLEORGERUND | FORAGEPARTICIPLEORGERUND | GAINPARTICIPLEORGERUND | GETPARTICIPLEORGERUND | GIFTPARTICIPLEORGERUND
| GOADPARTICIPLEORGERUND | INCUBATEPARTICIPLEORGERUND | INVESTIGATEPARTICIPLEORGERUND | KICKPARTICIPLEORGERUND | LEARNPARTICIPLEORGERUND | LEAVEPARTICIPLEORGERUND | LOOKPARTICIPLEORGERUND | LOSEPARTICIPLEORGERUND | NAMEPARTICIPLEORGERUND | MANIFESTPARTICIPLEORGERUND | MELDPARTICIPLEORGERUND | MILLPARTICIPLEORGERUND | MULTIPLYPARTICIPLEORGERUND | PAYPARTICIPLEORGERUND
| PLANESWALKPARTICIPLEORGERUND | PLAYPARTICIPLEORGERUND | POPULATEPARTICIPLEORGERUND | PREVENTPARTICIPLEORGERUND | PROLIFERATEPARTICIPLEORGERUND | PUTPARTICIPLEORGERUND | REGENERATEPARTICIPLEORGERUND | REMAINPARTICIPLEORGERUND | REMOVEPARTICIPLEORGERUND | RESOLVEPARTICIPLEORGERUND | RETURNPARTICIPLEORGERUND
| ROLLPARTICIPLEORGERUND | REVEALPARTICIPLEORGERUND | SACRIFICEPARTICIPLEORGERUND | SCRYPARTICIPLEORGERUND | SEARCHPARTICIPLEORGERUND | SEPARATEPARTICIPLEORGERUND | SHAREPARTICIPLEORGERUND | SHUFFLEPARTICIPLEORGERUND | SKIPPARTICIPLEORGERUND | SPENDPARTICIPLEORGERUND | SUPPORTPARTICIPLEORGERUND | SURVEILPARTICIPLEORGERUND
| SUBTRACTPARTICIPLEORGERUND | SUSPECTPARTICIPLEORGERUND | SUSPENDPARTICIPLEORGERUND | SWITCHPARTICIPLEORGERUND | TAKEPARTICIPLEORGERUND | TAPPARTICIPLEORGERUND | TARGETPARTICIPLEORGERUND | TEMPTPARTICIPLEORGERUND | TIMETRAVELPARTICIPLEORGERUND | TRANSFORMPARTICIPLEORGERUND | TRIGGERPARTICIPLEORGERUND | TURNPARTICIPLEORGERUND | VOTEPARTICIPLEORGERUND | WINPARTICIPLEORGERUND

verb_be.5: BEPRESENT | BEPAST | BEPARTICIPLEORGERUND | BEFUTURESUBJUNCTIVE | BEPLAIN
BEPRESENT.5: ("is"i | "are"i)
BEPAST.6: ("was"i | "were"i)
BEPARTICIPLEORGERUND.6: ("being"i | "been"i)
BEFUTURESUBJUNCTIVE.5: "would"i
BEPLAIN.0: "be"i

verb_have.5: HAVEPRESENT | HAVEPAST | HAVEPARTICIPLEORGERUND
HAVEPRESENT.5: ("have"i | "has"i)
HAVEPAST.6: "had"i
HAVEPARTICIPLEORGERUND.6: "having"i

verb_do.5: DOPRESENT | DOPAST | DOPARTICIPLEORGERUND
DOPRESENT.5: ("do"i | "does"i)
DOPAST.6: "did"i
DOPARTICIPLEORGERUND.6: ("doing"i | "done"i)

verb_may.5: "may"i
verb_must.5: "must"i

verb_become.5: BECOMEPRESENT | BECOMEPAST | BECOMEPARTICIPLEORGERUND
BECOMEPRESENT.5: "become"i["s"i]
BECOMEPAST.6: "became"i
BECOMEPARTICIPLEORGERUND.6: "becoming"i

verb_can.5: CANPRESENT | CANPAST
CANPRESENT.5: "can"i
CANPAST.6: "could"i

verb_abandon.5: ABANDONPRESENT | ABANDONPAST | ABANDONPARTICIPLEORGERUND
ABANDONPRESENT.5: "abandon"i["s"i]
ABANDONPAST.6: "abandoned"i
ABANDONPARTICIPLEORGERUND.6: "abandoning"i

verb_activate.5: ACTIVATEPRESENT | ACTIVATEPAST | ACTIVATEPARTICIPLEORGERUND
ACTIVATEPRESENT.5: "activate"i["s"i]
ACTIVATEPAST.6: "activated"i
ACTIVATEPARTICIPLEORGERUND.6: "activating"i

verb_adapt.5: ADAPTPRESENT | ADAPTPAST | ADAPTPARTICIPLEORGERUND
ADAPTPRESENT.5: "adapt"i["s"i]
ADAPTPAST.6: "adapted"i
ADAPTPARTICIPLEORGERUND.6: "adapting"i

verb_add.5: ADDPRESENT | ADDPAST | ADDPARTICIPLEORGERUND
ADDPRESENT.5: "add"i["s"i]
ADDPAST.6: "added"i
ADDPARTICIPLEORGERUND.6: "adding"i

verb_amass.5: AMASSPRESENT | AMASSPAST | AMASSPARTICIPLEORGERUND
AMASSPRESENT.5: "amass"i["s"i]
AMASSPAST.6: "amassed"i
AMASSPARTICIPLEORGERUND.6: "amassing"i

verb_assign.5: ASSIGNPRESENT | ASSIGNPAST | ASSIGNPARTICIPLEORGERUND
ASSIGNPRESENT.5: "assign"i["s"i]
ASSIGNPAST.6: "assigned"i
ASSIGNPARTICIPLEORGERUND.6: "assigning"i

verb_attach.5: ATTACHPRESENT | ATTACHPAST | ATTACHPARTICIPLEORGERUND
ATTACHPRESENT.5: "attach"i["s"i]
ATTACHPAST.6: "attached"i
ATTACHPARTICIPLEORGERUND.6: "attaching"i

verb_attack.5: ATTACKPRESENT | ATTACKPAST | ATTACKPARTICIPLEORGERUND
ATTACKPRESENT.5: "attack"i["s"i]
ATTACKPAST.6: "attacked"i
ATTACKPARTICIPLEORGERUND.6: "attacking"i

verb_block.5: BLOCKPRESENT | BLOCKPAST | BLOCKPARTICIPLEORGERUND
BLOCKPRESENT.5: "block"i["s"i]
BLOCKPAST.6: "blocked"i
BLOCKPARTICIPLEORGERUND.6: "blocking"i

verb_bolster.5: BOLSTERPRESENT | BOLSTERPAST | BOLSTERPARTICIPLEORGERUND
BOLSTERPRESENT.5: "bolster"i["s"i]
BOLSTERPAST.6: "bolstered"i
BOLSTERPARTICIPLEORGERUND.6: "bolstering"i

verb_cast.5: CASTPRESENT | CASTPAST | CASTPARTICIPLEORGERUND
CASTPRESENT.5: "cast"i["s"i]
CASTPAST.6: "casted"i
CASTPARTICIPLEORGERUND.6: "casting"i

verb_cause.5: CAUSEPRESENT | CAUSEPAST | CAUSEPARTICIPLEORGERUND
CAUSEPRESENT.5: "cause"i["s"i]
CAUSEPAST.6: "caused"i
CAUSEPARTICIPLEORGERUND.6: "causing"i

verb_change.5: CHANGEPRESENT | CHANGEPAST | CHANGEPARTICIPLEORGERUND
CHANGEPRESENT.5: "change"i["s"i]
CHANGEPAST.6: "changed"i
CHANGEPARTICIPLEORGERUND.6: "changing"i

verb_choose.5: CHOOSEPRESENT | CHOOSEPAST | CHOOSEPARTICIPLEORGERUND
CHOOSEPRESENT.5: "choose"i["s"i]
CHOOSEPAST.6: "chose"i
CHOOSEPARTICIPLEORGERUND.6: "choosing"i | "chosen"i

verb_clash.5: CLASHPRESENT | CLASHPAST | CLASHPARTICIPLEORGERUND
CLASHPRESENT.5: "clash"i["s"i]
CLASHPAST.6: "clashed"i
CLASHPARTICIPLEORGERUND.6: "clashing"i

verb_cloak.5: CLOAKPRESENT | CLOAKPAST | CLOAKPARTICIPLEORGERUND
CLOAKPRESENT.5: "cloak"i["s"i]
CLOAKPAST.6: "cloaked"i
CLOAKPARTICIPLEORGERUND.6: "cloaking"i

verb_collect.5: COLLECTPRESENT | COLLECTPAST | COLLECTPARTICIPLEORGERUND
COLLECTPRESENT.5: "collect"i["s"i]
COLLECTPAST.6: "collected"i
COLLECTPARTICIPLEORGERUND.6: "collecting"i

verb_connive.5: CONNIVEPRESENT | CONNIVEPAST | CONNIVEPARTICIPLEORGERUND
CONNIVEPRESENT.5: "connive"i["s"i]
CONNIVEPAST.6: "connived"i
CONNIVEPARTICIPLEORGERUND.6: "conniving"i

verb_control.5: CONTROLPRESENT | CONTROLPAST | CONTROLPARTICIPLEORGERUND
CONTROLPRESENT.5: "control"i["s"i]
CONTROLPAST.6: "controlled"i
CONTROLPARTICIPLEORGERUND.6: "controlling"i

verb_copy.5: COPYPRESENT | COPYPAST | COPYPARTICIPLEORGERUND
COPYPRESENT.5: "copy"i | "copies"i
COPYPAST.6: "copied"i
COPYPARTICIPLEORGERUND.6: "copying"i

verb_counter.5: COUNTERPRESENT | COUNTERPAST | COUNTERPARTICIPLEORGERUND
COUNTERPRESENT.5: "counter"i["s"i]
COUNTERPAST.6: "countered"i
COUNTERPARTICIPLEORGERUND.6: "countering"i

verb_create.5: CREATEPRESENT | CREATEPAST | CREATEPARTICIPLEORGERUND
CREATEPRESENT.5: "create"i["s"i]
CREATEPAST.6: "created"i
CREATEPARTICIPLEORGERUND.6: "creating"i

verb_cost.5: COSTPRESENT | COSTPARTICIPLEORGERUND
COSTPRESENT.5: "cost"i["s"i]
COSTPARTICIPLEORGERUND.6: "costing"i

verb_cycle.5: CYCLEPRESENT | CYCLEPAST | CYCLEPARTICIPLEORGERUND
CYCLEPRESENT.5: "cycle"i["s"i]
CYCLEPAST.6: "cycled"i
CYCLEPARTICIPLEORGERUND.6: "cycling"i

verb_deal.5: DEALPRESENT | DEALPAST | DEALPARTICIPLEORGERUND
DEALPRESENT.5: "deal"i["s"i]
DEALPAST.6: "dealt"i
DEALPARTICIPLEORGERUND.6: "dealing"i

verb_declare.5: DECLAREPRESENT | DECLAREPAST | DECLAREPARTICIPLEORGERUND
DECLAREPRESENT.5: "declare"i["s"i]
DECLAREPAST.6: "declared"i
DECLAREPARTICIPLEORGERUND.6: "declaring"i

verb_destroy.5: DESTROYPRESENT | DESTROYPAST | DESTROYPARTICIPLEORGERUND
DESTROYPRESENT.5: "destroy"i["s"i]
DESTROYPAST.6: "destroyed"i
DESTROYPARTICIPLEORGERUND.6: "destroying"i

verb_detain.5: DETAINPRESENT | DETAINPAST | DETAINPARTICIPLEORGERUND
DETAINPRESENT.5: "detain"i["s"i]
DETAINPAST.6: "detained"i
DETAINPARTICIPLEORGERUND.6: "detaining"i

verb_die.5: DIEPRESENT | DIEPAST | DIEPARTICIPLEORGERUND
DIEPRESENT.5: "die"i["s"i]
DIEPAST.6: "died"i
DIEPARTICIPLEORGERUND.6: "dying"i

verb_discard.5: DISCARDPRESENT | DISCARDPAST | DISCARDPARTICIPLEORGERUND
DISCARDPRESENT.5: "discard"i["s"i]
DISCARDPAST.6: "discarded"i
DISCARDPARTICIPLEORGERUND.6: "discarding"i

verb_discover.5: DISCOVERPRESENT | DISCOVERPAST | DISCOVERPARTICIPLEORGERUND
DISCOVERPRESENT.5: "discover"i["s"i]
DISCOVERPAST.6: "discovered"i
DISCOVERPARTICIPLEORGERUND.6: "discovering"i

verb_divide.5: DIVIDEPRESENT | DIVIDEPAST | DIVIDEPARTICIPLEORGERUND
DIVIDEPRESENT.5: "divide"i["s"i]
DIVIDEPAST.6: "divided"i
DIVIDEPARTICIPLEORGERUND.6: "dividing"i


verb_double.5: DOUBLEPRESENT | DOUBLEPAST | DOUBLEPARTICIPLEORGERUND
DOUBLEPRESENT.5: "double"i["s"i]
DOUBLEPAST.6: "doubled"i
DOUBLEPARTICIPLEORGERUND.6: "doubling"i

verb_draw.5: DRAWPRESENT | DRAWPAST | DRAWPARTICIPLEORGERUND
DRAWPRESENT.5: "draw"i["s"i]
DRAWPAST.6: "drawed"i
DRAWPARTICIPLEORGERUND.6: "drawing"i

verb_enter.5: ENTERPRESENT | ENTERPAST | ENTERPARTICIPLEORGERUND
ENTERPRESENT.5: "enter"i["s"i]
ENTERPAST.6: "entered"i
ENTERPARTICIPLEORGERUND.6: "entering"i

verb_enchant.5: ENCHANTPRESENT | ENCHANTPAST | ENCHANTPARTICIPLEORGERUND
ENCHANTPRESENT.5: "enchant"i["s"i]
ENCHANTPAST.10: "enchanted"i
ENCHANTPARTICIPLEORGERUND.10: "enchanting"i

verb_equip.5: EQUIPPRESENT | EQUIPPAST | EQUIPPARTICIPLEORGERUND
EQUIPPRESENT.5: "equip"i["s"i]
EQUIPPAST.6: "equipped"i
EQUIPPARTICIPLEORGERUND.6: "equipping"i

verb_exchange.5: EXCHANGEPRESENT | EXCHANGEPAST | EXCHANGEPARTICIPLEORGERUND
EXCHANGEPRESENT.5: "exchange"i["s"i]
EXCHANGEPAST.6: "exchanged"i
EXCHANGEPARTICIPLEORGERUND.6: "exchanging"i

verb_exert.5: EXERTPRESENT | EXERTPAST | EXERTPARTICIPLEORGERUND
EXERTPRESENT.5: "exert"i["s"i]
EXERTPAST.6: "exerted"i
EXERTPARTICIPLEORGERUND.6: "exerting"i

verb_exile.5: EXILEPRESENT | EXILEPAST | EXILEPARTICIPLEORGERUND
EXILEPRESENT.15: "exile"i["s"i]
EXILEPAST.20: "exiled"i
EXILEPARTICIPLEORGERUND.6: "exiling"i

verb_explore.5: EXPLOREPRESENT | EXPLOREPAST | EXPLOREPARTICIPLEORGERUND
EXPLOREPRESENT.5: "explore"i["s"i]
EXPLOREPAST.6: "explored"i
EXPLOREPARTICIPLEORGERUND.6: "exploring"i

verb_fateseal.5: FATESEALPRESENT | FATESEALPAST | FATESEALPARTICIPLEORGERUND
FATESEALPRESENT.5: "fateseal"i["s"i]
FATESEALPAST.6: "fatesealed"i
FATESEALPARTICIPLEORGERUND.6: "fatesealing"i

verb_fight.5: FIGHTPRESENT | FIGHTPAST | FIGHTPARTICIPLEORGERUND
FIGHTPRESENT.5: "fight"i["s"i]
FIGHTPAST.6: "fought"i
FIGHTPARTICIPLEORGERUND.6: "fighting"i

verb_flip.5: FLIPPRESENT | FLIPPAST | FLIPPARTICIPLEORGERUND
FLIPPRESENT.5: "flip"i["s"i]
FLIPPAST.6: "flipped"i
FLIPPARTICIPLEORGERUND.6: "flipping"i

verb_forage.5: FORAGEPRESENT | FORAGEPAST | FORAGEPARTICIPLEORGERUND
FORAGEPRESENT.5: "forage"i["s"i]
FORAGEPAST.6: "foraged"i
FORAGEPARTICIPLEORGERUND.6: "foraging"i

verb_gain.5: GAINPRESENT | GAINPAST | GAINPARTICIPLEORGERUND
GAINPRESENT.5: "gain"i["s"i]
GAINPAST.6: "gained"i
GAINPARTICIPLEORGERUND.6: "gaining"i

verb_get.5: GETPRESENT | GETPAST | GETPARTICIPLEORGERUND
GETPRESENT.5: "get"i["s"i]
GETPAST.6: "got"i
GETPARTICIPLEORGERUND.6: "getting"i

verb_gift.5: GIFTPRESENT | GIFTPAST | GIFTPARTICIPLEORGERUND
GIFTPRESENT.5: "gift"i["s"i]
GIFTPAST.6: "gifted"i
GIFTPARTICIPLEORGERUND.6: "gifting"i

verb_goad.5: GOADPRESENT | GOADPAST | GOADPARTICIPLEORGERUND
GOADPRESENT.5: "goad"i["s"i]
GOADPAST.6: "goaded"i
GOADPARTICIPLEORGERUND.6: "goading"i

verb_incubate.5: INCUBATEPRESENT | INCUBATEPAST | INCUBATEPARTICIPLEORGERUND
INCUBATEPRESENT.5: "incubate"i["s"i]
INCUBATEPAST.6: "incubated"i
INCUBATEPARTICIPLEORGERUND.6: "incubating"i

verb_investigate.5: INVESTIGATEPRESENT | INVESTIGATEPAST | INVESTIGATEPARTICIPLEORGERUND
INVESTIGATEPRESENT.5: "investigate"i["s"i]
INVESTIGATEPAST.6: "investigated"i
INVESTIGATEPARTICIPLEORGERUND.6: "investigating"i

verb_kick.5: KICKPRESENT | KICKPAST | KICKPARTICIPLEORGERUND
KICKPRESENT.5: "kick"i["s"i]
KICKPAST.6: "kicked"i
KICKPARTICIPLEORGERUND.6: "kicking"i

verb_learn.5: LEARNPRESENT | LEARNPAST | LEARNPARTICIPLEORGERUND
LEARNPRESENT.5: "learn"i["s"i]
LEARNPAST.6: "learned"i
LEARNPARTICIPLEORGERUND.6: "learning"i

verb_leave.5: LEAVEPRESENT | LEAVEPAST | LEAVEPARTICIPLEORGERUND
LEAVEPRESENT.5: "leave"i["s"i]
LEAVEPAST.6: "left"i
LEAVEPARTICIPLEORGERUND.6: "leaving"i

verb_look.5: LOOKPRESENT | LOOKPAST | LOOKPARTICIPLEORGERUND
LOOKPRESENT.5: "look"i["s"i]
LOOKPAST.6: "looked"i
LOOKPARTICIPLEORGERUND.6: "looking"i

verb_lose.5: LOSEPRESENT | LOSEPAST | LOSEPARTICIPLEORGERUND
LOSEPRESENT.5: "lose"i["s"i]
LOSEPAST.6: "lost"i
LOSEPARTICIPLEORGERUND.6: "losing"i

verb_name.5: NAMEPRESENT | NAMEPAST | NAMEPARTICIPLEORGERUND
NAMEPRESENT.5: "name"i["s"i]
NAMEPAST.6: "named"i
NAMEPARTICIPLEORGERUND.6: "naming"i

verb_manifest.5: MANIFESTPRESENT | MANIFESTPAST | MANIFESTPARTICIPLEORGERUND
MANIFESTPRESENT.5: "manifest"i["s"i]
MANIFESTPAST.6: "manifested"i
MANIFESTPARTICIPLEORGERUND.6: "manifesting"i

verb_meld.5: MELDPRESENT | MELDPAST | MELDPARTICIPLEORGERUND
MELDPRESENT.5: "meld"i["s"i]
MELDPAST.6: "melded"i
MELDPARTICIPLEORGERUND.6: "melding"i

verb_mill.5: MILLPRESENT | MILLPAST | MILLPARTICIPLEORGERUND
MILLPRESENT.5: "mill"i["s"i]
MILLPAST.6: "milled"i
MILLPARTICIPLEORGERUND.6: "milling"i

verb_multiply.5: MULTIPLYPRESENT | MULTIPLYPAST | MULTIPLYPARTICIPLEORGERUND
MULTIPLYPRESENT.5: "multiply"i | "multiplies"i
MULTIPLYPAST.6: "multiplied"i
MULTIPLYPARTICIPLEORGERUND.6: "multiplying"i

verb_pay.5: PAYPRESENT | PAYPAST | PAYPARTICIPLEORGERUND
PAYPRESENT.5: "pay"i["s"i]
PAYPAST.6: "paid"i
PAYPARTICIPLEORGERUND.6: "paying"i

verb_planeswalk.5: PLANESWALKPRESENT | PLANESWALKPAST | PLANESWALKPARTICIPLEORGERUND
PLANESWALKPRESENT.5: "planeswalk"i["s"i]
PLANESWALKPAST.6: "planeswalked"i
PLANESWALKPARTICIPLEORGERUND.6: "planeswalking"i

verb_play.5: PLAYPRESENT | PLAYPAST | PLAYPARTICIPLEORGERUND
PLAYPRESENT.5: "play"i["s"i]
PLAYPAST.6: "played"i
PLAYPARTICIPLEORGERUND.6: "playing"i

verb_populate.5: POPULATEPRESENT | POPULATEPAST | POPULATEPARTICIPLEORGERUND
POPULATEPRESENT.5: "populate"i["s"i]
POPULATEPAST.6: "populated"i
POPULATEPARTICIPLEORGERUND.6: "populating"i

verb_prevent.5: PREVENTPRESENT | PREVENTPAST | PREVENTPARTICIPLEORGERUND
PREVENTPRESENT.5: "prevent"i["s"i]
PREVENTPAST.6: "prevented"i
PREVENTPARTICIPLEORGERUND.6: "preventing"i

verb_proliferate.5: PROLIFERATEPRESENT | PROLIFERATEPAST | PROLIFERATEPARTICIPLEORGERUND
PROLIFERATEPRESENT.5: "proliferate"i["s"i]
PROLIFERATEPAST.6: "proliferated"i
PROLIFERATEPARTICIPLEORGERUND.6: "proliferating"i

verb_put.5: PUTPRESENT | PUTPAST | PUTPARTICIPLEORGERUND
PUTPRESENT.5: "put"i["s"i]
PUTPAST.6: "put"i
PUTPARTICIPLEORGERUND.6: "putting"i

verb_regenerate.5: REGENERATEPRESENT | REGENERATEPAST | REGENERATEPARTICIPLEORGERUND
REGENERATEPRESENT.5: "regenerate"i["s"i]
REGENERATEPAST.6: "regenerated"i
REGENERATEPARTICIPLEORGERUND.6: "regenerating"i

verb_remain.5: REMAINPRESENT | REMAINPAST | REMAINPARTICIPLEORGERUND
REMAINPRESENT.5: "remain"i["s"i]
REMAINPAST.6: "remained"i
REMAINPARTICIPLEORGERUND.6: "remaining"i

verb_remove.5: REMOVEPRESENT | REMOVEPAST | REMOVEPARTICIPLEORGERUND
REMOVEPRESENT.5: "remove"i["s"i]
REMOVEPAST.6: "removed"i
REMOVEPARTICIPLEORGERUND.6: "removing"i

verb_resolve.5: RESOLVEPRESENT | RESOLVEPAST | RESOLVEPARTICIPLEORGERUND
RESOLVEPRESENT.5: "resolve"i["s"i]
RESOLVEPAST.6: "resolved"i
RESOLVEPARTICIPLEORGERUND.6: "resolving"i

verb_return.5: RETURNPRESENT | RETURNPAST | RETURNPARTICIPLEORGERUND
RETURNPRESENT.5: "return"i["s"i]
RETURNPAST.6: "returned"i
RETURNPARTICIPLEORGERUND.6: "returning"i

verb_roll.5: ROLLPRESENT | ROLLPAST | ROLLPARTICIPLEORGERUND
ROLLPRESENT.5: "roll"i["s"i]
ROLLPAST.6: "rolled"i
ROLLPARTICIPLEORGERUND.6: "rolling"i

verb_reveal.5: REVEALPRESENT | REVEALPAST | REVEALPARTICIPLEORGERUND
REVEALPRESENT.5: "reveal"i["s"i]
REVEALPAST.6: "revealed"i
REVEALPARTICIPLEORGERUND.6: "revealing"i

verb_sacrifice.5: SACRIFICEPRESENT | SACRIFICEPAST | SACRIFICEPARTICIPLEORGERUND
SACRIFICEPRESENT.5: "sacrifice"i["s"i]
SACRIFICEPAST.6: "sacrificed"i
SACRIFICEPARTICIPLEORGERUND.6: "sacrificing"i

verb_scry.5: SCRYPRESENT | SCRYPAST | SCRYPARTICIPLEORGERUND
SCRYPRESENT.5: "scry"i["s"i]
SCRYPAST.6: "scryed"i
SCRYPARTICIPLEORGERUND.6: "scrying"i

verb_search.5: SEARCHPRESENT | SEARCHPAST | SEARCHPARTICIPLEORGERUND
SEARCHPRESENT.5: "search"i["s"i]
SEARCHPAST.6: "searched"i
SEARCHPARTICIPLEORGERUND.6: "searching"i

verb_setinmotion.5: SETINMOTIONPRESENT //TODO.5: Needs to handle "if you set a scheme in motion"
SETINMOTIONPRESENT.5: "set in motion"

verb_separate.5: SEPARATEPRESENT | SEPARATEPAST | SEPARATEPARTICIPLEORGERUND
SEPARATEPRESENT.5: "separate"i["s"i]
SEPARATEPAST.6: "separated"i
SEPARATEPARTICIPLEORGERUND.6: "separating"i

verb_share.5: SHAREPRESENT | SHAREPAST | SHAREPARTICIPLEORGERUND
SHAREPRESENT.5: "share"i["s"i]
SHAREPAST.6: "shared"i
SHAREPARTICIPLEORGERUND.6: "sharing"i

verb_shuffle.5: SHUFFLEPRESENT | SHUFFLEPAST | SHUFFLEPARTICIPLEORGERUND
SHUFFLEPRESENT.5: "shuffle"i["s"i]
SHUFFLEPAST.6: "shuffled"i
SHUFFLEPARTICIPLEORGERUND.6: "shuffling"i

verb_skip.5: SKIPPRESENT | SKIPPAST | SKIPPARTICIPLEORGERUND
SKIPPRESENT.5: "skip"i["s"i]
SKIPPAST.6: "skipped"i
SKIPPARTICIPLEORGERUND.6: "skipping"i

verb_spend.5: SPENDPRESENT | SPENDPAST | SPENDPARTICIPLEORGERUND
SPENDPRESENT.5: "spend"i["s"i]
SPENDPAST.6: "spent"i
SPENDPARTICIPLEORGERUND.6: "spending"i

verb_support.5: SUPPORTPRESENT | SUPPORTPAST | SUPPORTPARTICIPLEORGERUND
SUPPORTPRESENT.5: "support"i["s"i]
SUPPORTPAST.6: "supported"i
SUPPORTPARTICIPLEORGERUND.6: "supporting"i

verb_surveil.5: SURVEILPRESENT | SURVEILPAST | SURVEILPARTICIPLEORGERUND
SURVEILPRESENT.5: "surveil"i["s"i]
SURVEILPAST.6: "surveiled"i
SURVEILPARTICIPLEORGERUND.6: "surveiling"i

verb_suspect.5: SUSPECTPRESENT | SUSPECTPAST | SUSPECTPARTICIPLEORGERUND
SUSPECTPRESENT.5: "suspect"i["s"i]
SUSPECTPAST.6: "suspected"i
SUSPECTPARTICIPLEORGERUND.6: "suspecting"i

verb_subtract.5: SUBTRACTPRESENT | SUBTRACTPAST | SUBTRACTPARTICIPLEORGERUND
SUBTRACTPRESENT.5: "subtract"i["s"i]
SUBTRACTPAST.6: "subtracted"i
SUBTRACTPARTICIPLEORGERUND.6: "subtracting"i

verb_suspend.5: SUSPENDPRESENT | SUSPENDPAST | SUSPENDPARTICIPLEORGERUND
SUSPENDPRESENT.5: "suspend"i["s"i]
SUSPENDPAST.6: "suspended"i
SUSPENDPARTICIPLEORGERUND.6: "suspending"i

verb_switch.5: SWITCHPRESENT | SWITCHPAST | SWITCHPARTICIPLEORGERUND
SWITCHPRESENT.5: "switch"i["s"i]
SWITCHPAST.6: "switched"i
SWITCHPARTICIPLEORGERUND.6: "switching"i

verb_take.5: TAKEPRESENT | TAKEPAST | TAKEPARTICIPLEORGERUND
TAKEPRESENT.5: "take"i["s"i]
TAKEPAST.6: "took"i
TAKEPARTICIPLEORGERUND.6: "taking"i

verb_tap.5: TAPPRESENT | TAPPAST | TAPPARTICIPLEORGERUND
TAPPRESENT.5: "un"i? "tap"i["s"i]
TAPPAST.6: "un"i? "tapped"i
TAPPARTICIPLEORGERUND.6: "un"i? "tapping"i

verb_target.5: TARGETPRESENT | TARGETPAST | TARGETPARTICIPLEORGERUND
TARGETPRESENT.5: "target"i["s"i]
TARGETPAST.6: "targeted"i
TARGETPARTICIPLEORGERUND.6: "targeting"i

verb_tempt.5: TEMPTPRESENT | TEMPTPAST | TEMPTPARTICIPLEORGERUND
TEMPTPRESENT.5: "tempt"i["s"i]
TEMPTPAST.6: "tempted"i
TEMPTPARTICIPLEORGERUND.6: "tempting"i

verb_timetravel.5: TIMETRAVELPRESENT | TIMETRAVELPAST | TIMETRAVELPARTICIPLEORGERUND
TIMETRAVELPRESENT.5: "time travel"i["s"i]
TIMETRAVELPAST.6: "time traveled"i
TIMETRAVELPARTICIPLEORGERUND.6: "time traveling"i

verb_transform.5: TRANSFORMPRESENT | TRANSFORMPAST | TRANSFORMPARTICIPLEORGERUND
TRANSFORMPRESENT.5: "transform"i["s"i]
TRANSFORMPAST.6: "transformed"i
TRANSFORMPARTICIPLEORGERUND.6: "transforming"i

verb_trigger.5: TRIGGERPRESENT | TRIGGERPAST | TRIGGERPARTICIPLEORGERUND
TRIGGERPRESENT.5: "trigger"i["s"i]
TRIGGERPAST.6: "triggered"i
TRIGGERPARTICIPLEORGERUND.6: "triggering"i

verb_turn.5: TURNPRESENT | TURNPAST | TURNPARTICIPLEORGERUND
TURNPRESENT.5: "turn"i["s"i] ("face-up" | "face-down")
TURNPAST.6: "turned"i ("face-up" | "face-down")
TURNPARTICIPLEORGERUND.6: "turning"i

verb_vote.5: VOTEPRESENT | VOTEPAST | VOTEPARTICIPLEORGERUND
VOTEPRESENT.5: "vote"i["s"i]
VOTEPAST.6: "voted"i
VOTEPARTICIPLEORGERUND.6: "voting"i

verb_win.5: WINPRESENT | WINPAST | WINPARTICIPLEORGERUND
WINPRESENT.5: "win"i["s"i]
WINPAST.6: "won"i
WINPARTICIPLEORGERUND.6: "winning"i