# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Magic Set Test Coverage (Weekly)

on:
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov pytest-xdist
        python -m pip install --upgrade setuptools setuptools_scm wheel gdown
        python -m pip install .
    - name: Fetch copy of AllPrintings.json from Google Drive
      run: |
        gdown https://drive.google.com/file/d/1ZTTotLkZl-nLIDc7LgK6PpkVN7RzQ0DB/view?usp=sharing
    - name: Test Magic set coverage with pytest
      run: |
        pytest -n 8 tests/parsing/test_mtgjson_setparsing.py

